sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: michael@allen.digital
  api_key:
    secure: LPFwapt6UXRQ2ZkdRluAUMsaNT9F/Q54zOiXbkfjtDF4MkHxXssH9iDWRwXYocxKnaiD3/kli97e+wlQZqVvgjxidzS0JAXO5BbqW0NZ179IrYW4UeAcrnRvRb+VhkxyDVQRReCpnyUjjXJH+ZGZ/VK/hYCjh2hwo5GdCAsUjcgRtLxoWunv7fIX2KdGXAHEz8nBnFLCB+K9UmXFdn7/yFJfUOXEgw8JUPgjU8oJcJWVE3rEppSqXQGEALY/uzB1O+7bnWUfiqAV8+NURdX9Qnc8u4zsUM3pg0aEmNtsb2AfHMYcUFOjFsbQIrdaRbN3Udxuf654GzkrNTcdvGkhyRMOqQ5lxtD0WDY6u5kJGx5sabV2jgjljOdnfLhONf+UJLEOrbfFFd72bVpV7Gs4voyMzI32LhNFWu20RQI5scZm4bn7xGpB/CyXL/XsNlEIfIIRR8q0kr1FhXVYL4dmzIQhDJriJuVHU6OT/W35oRluelI9r/hQQBAapAGl9GyQOykaZ+mAmZWRHqynuomLQJZ4VX4R+bB8R5/47JmLvQQ8d82cEfzf+0VDUiBbF2gVDuCMCGcCtsSP4NzUUWEcgoInEE2hh7o9toah17YrdKrmW9evT0NMczpjgtd3FvuZAsb/9EGi1+isI6JBFclDP+2xKXVwCu28l3X9OkdhBPc=
  on:
    tags: true
    repo: hmcts/look-and-feel
